services:
  database:
    container_name: postgres-eventos
    image: postgres:16.4
    restart: no
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data: